controller session created
OUMAREGA/IPSSIProjectNode pull request #22
Opened 2020-02-02 20:22 UTC by OumarCh

# Description

Création du controller de session

**Cocher les mentions utiles**

- [ ] Correction d'un bug
- * Nouvelle fonctionnalité
- [ ] Changements critiques

Décrire les tests qui ont été effectués

**Configuration de test**
* Système d'exploitation :
* Version utilisée :

2020-02-02 20:41 UTC, ii02735 requested changes

2020-02-02 20:41 UTC, ii02735 commented on src/controllers/sessionController.js
> +        res.json({message: "Il manque des infos"});
Plutôt que d'écrire "il manque des infos", ne serait-il pas mieux que de renvoyer les informations manquantes ?
Les informations manquantes sont **récoltées dans error**. (regarder comment elles sont affichées dans **UserController.js**)
Il aurait été préférable finalement, plutôt que d'écrire dans le schéma Session **required:true**, écrire des messages personnalisés, comme pour **UserModel.js**

2020-02-02 20:41 UTC, ii02735 commented on src/controllers/sessionController.js
> +      if(error){
Il faudrait aussi vérifier le cas où la base de données ne renvoie rien. Soit lorsque sessions est vide.
Dans ce cas, renvoyer une erreur 404

2020-02-02 20:41 UTC, ii02735 commented on src/controllers/sessionController.js
> +        if(error){
En réalité ici, ce n'est pas error qui permet de déterminer si rien n'a été trouvé, mais **session**
Si aucune session n'a été trouvé, mongoose renvoie une **valeur *null***. Or il ne s'agit pas d'une erreur puisqu'il s'agit d'une valeur.
Donc il faudrait plutôt vérifier **si session null** et dans ce cas renvoyer une erreur 404

2020-02-02 20:41 UTC, ii02735 commented on src/controllers/sessionController.js
> +        if(error){
Idem pour ici aussi

2020-02-02 20:41 UTC, ii02735 commented on src/controllers/sessionController.js
> +        if(error){
Idem ici aussi

2020-02-02 20:41 UTC, ii02735 commented on src/controllers/sessionController.js
> +          res.json({message: "Session supprimé"})
Session **supprimée**

2020-02-02 20:43 UTC, ii02735 commented on src/controllers/sessionController.js
> +        res.json({message: "Il manque des infos"});
Un exemple avec **UserController**, si des erreurs sont manquantes, la réponse de l'API sera la suivante :
```json
{
    "roleId": "L'id du rôle est requis",
    "firstname": "Le prénom de l'utilisateur est requis",
    "name": "Le nom de l'utilisateur est requis"
}
```

Plutôt que 
```json
{ "message": "Il manque des infos" }
```

2020-02-02 21:17 UTC, OumarCh commented on src/controllers/sessionController.js
> +        res.json({message: "Il manque des infos"});
Ok !

2020-02-02 21:17 UTC, OumarCh commented on src/controllers/sessionController.js
> +      if(error){
Pas de problème

2020-02-02 21:52 UTC, ii02735 requested changes

2020-02-02 21:52 UTC, ii02735 commented on src/controllers/sessionController.js
> +      else if(!sessions){
Attention, pour vérifier si le tableau est vide : **sessions.length == 0**
Ici !sessions équivaut à sessions == null, or *ce n'est pas vrai* puisque le tableau **existe mais est vide**

2020-02-02 21:52 UTC, ii02735 commented on src/controllers/sessionController.js
>            res.json({message: "Id introuvable"});
Préférer **session introuvable** : plus de signification

2020-02-02 21:52 UTC, ii02735 commented on src/controllers/sessionController.js
>            res.json({message: "Id introuvable"});
Préférer **session introuvable** : plus de signification

2020-02-02 21:52 UTC, ii02735 commented on src/controllers/sessionController.js
>            res.json({message: "Id introuvable"});
Préférer **session introuvable** : plus de signification

2020-02-08 22:53 UTC, ii02735 approved these changes

2020-02-08 23:11 UTC, ii02735 approved these changes

2020-02-08 23:35 UTC, merged